### PR TITLE
18086 Install MCE alongside ACM

### PR DESCRIPTION
**Pull request by zkayyali812**
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>
/hold
https://github.com/open-cluster-management/backlog/issues/18086

### CODE REVIEW

**Review by JakobGray — COMMENTED** [review]
Are there some CRDs that need to be pulled out of what mch-operator gathers from hub-crds?

**Comment by zkayyali812** [comment]
@JakobGray Yes! Great catch. 

The CRDs here should be removed - https://github.com/open-cluster-management/hub-crds/tree/main/crds/foundation
I'll create a release-9.9 branch in hub-crds and remove the foundation CRDs there.

**Pull request merged**
