### PR TITLE
Enable cluster-proxy-addon in ACM

### PR DESCRIPTION
**Pull request by skeeey**
Signed-off-by: liuwei <liuweixa@redhat.com>

### CODE REVIEW

**Comment by JakobGray** [comment]
@skeeey Cluster-proxy-addon was added to the installer last week https://github.com/open-cluster-management/multiclusterhub-operator/pull/652. Currently it's installed by default, so it still needs a toggle to disable by default. Can you verify that it is running as expected on the latest builds?

**Comment by JakobGray** [comment]
@skeeey I've opened a new PR with toggle support based off of this one to update the component: https://github.com/open-cluster-management/multiclusterhub-operator/pull/655

**Comment by skeeey** [comment]
@JakobGray cool, thank you

**Pull request closed without merging**
