### PR TITLE
update foundation role

### PR DESCRIPTION
**Pull request by ldpliu**
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/open-cluster-management/backlog/issues/14072
https://github.com/open-cluster-management/multicloud-operators-foundation/pull/399

### CODE REVIEW

**Comment by JakobGray** [comment]
@ldpliu This will need to go in https://github.com/open-cluster-management/backplane-operator/blob/main/pkg/templates/charts/server-foundation/templates/clusterrole-foundation.yaml, right?

**Comment by ldpliu** [comment]
> @ldpliu This will need to go in https://github.com/open-cluster-management/backplane-operator/blob/main/pkg/templates/charts/server-foundation/templates/clusterrole-foundation.yaml, right?

sure, we still working on this pr, if it is merged, I will submit pr to backplane-operator.

**Review by zkayyali812 — APPROVED** [review]

**Pull request merged**
