### PR TITLE
Fix xDescriptors

### PR DESCRIPTION
**Pull request by zkayyali812**
/hold

https://github.com/open-cluster-management/backlog/issues/17765
Awaiting Approval

Updates xDescriptors for boolean fields to match - https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#3-k8sResourcePrefix

### CODE REVIEW

**Review by JakobGray — APPROVED** [review]

**Comment by JakobGray** [comment]
We'll want this in 2.4 as well once 2.4.2 opens up for changes

**Comment by JakobGray** [comment]
@zkayyali812 Is this good to merge?

**Comment by zkayyali812** [comment]
@JakobGray 
This is good to merge.
I assume we should get this into the 2.4.2 stream as well?

**Comment by JakobGray** [comment]
Yes release-2.4 is open for commits now

**Pull request merged**
