### PR TITLE
Remove cert-manager components

### PR DESCRIPTION
**Pull request by JakobGray**
Issue: https://github.com/open-cluster-management/backlog/issues/12080

### CODE REVIEW

**Comment by JakobGray** [comment]
The file skipping in `pkg/rendering/crd_renderer.go` can be removed once the CRDs have been pulled from hub-crds

**Comment by zkayyali812** [comment]
@JakobGray Should this PR also deprecate flag - `separateCertificateManagement`?

**Comment by zkayyali812** [comment]
/lgtm

I see in your linked issue,  you plan to do it in next PR

**Pull request merged**
