### PR TITLE
Upgrade to Operator-SDK v1.9.0

### PR DESCRIPTION
**Pull request by zkayyali812**
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>

Do not merge. Branch is based off main for now to be able to pull in and manage changes as they come in easier.

### CODE REVIEW

**Comment by zkayyali812** [comment]
Mock PR test will likely fail until it is merged in, since the file location has since changed.

**Comment by JakobGray** [comment]
@zkayyali812 The [installation doc](https://github.com/zkayyali812/multiclusterhub-operator/blob/operator-sdk-1.9.0/docs/installation.md#deploy-multiclusterhub-instance) still references `make cr` as the way to create the mch instance, but that target is removed. Should it be added back or is there a new way to create the instance?

**Comment by zkayyali812** [comment]
@JakobGray I didnt move that make target over. Although perhaps I should. Since samples are stored by default in `config/samples`, `oc apply -k config/samples`, would apply the custom resources

**Review by JakobGray — APPROVED** [review]

**Pull request merged**
