### PR TITLE
permission fix for 2.1 cluster-manager-admin

### PR DESCRIPTION
**Pull request by Randy424**
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>

regarding: https://github.com/open-cluster-management/backlog/issues/11596

### CODE REVIEW

**Comment by Randy424** [comment]
/assign @zkayyali812
✌🏾

**Comment by Randy424** [comment]
`needs-rebase` was added because the PR was accidentally opened against main, when it should have been opened against 2.1 initially. I think it's keeping me from `/retest`'ing

**Comment by zkayyali812** [comment]
Hi @Randy424 ! Please close out this PR and open this as a branch instead of a fork. That will allow the jobs to run as intended.

**Comment by Randy424** [comment]
@zkayyali812 Gotcha, I don't actually have write access to the repo atm, could you add me as a contributor?

**Pull request closed without merging**
