### PR TITLE
remove ocm klusterlet cert secret

### PR DESCRIPTION
**Pull request by zhiweiyin318**
issue: https://github.com/open-cluster-management/backlog/issues/13329

remove the cert secret `ocm-klusterlet-self-signed-secrets` since ocm-controller creates it and maintains its rotation now.

### CODE REVIEW

**Comment by JakobGray** [comment]
I'm seeing "Enforcing pod volumes" repeated in the logs
```
{"level":"info","ts":1624453195.7626147,"msg":"Enforcing pod volumes","Deployment.Namespace":"open-cluster-management","Deployment.Name":"ocm-webhook"}
{"level":"info","ts":1624453195.908394,"logger":"controller_multiclusterhub","msg":"Ensuring managed cluster hub resources are removed"}
{"level":"info","ts":1624453196.0306098,"logger":"controller_multiclusterhub","msg":"Reconciling MultiClusterHub","Request.Namespace":"open-cluster-management","Request.Name":"multiclusterhub"}
{"level":"info","ts":1624453196.054841,"logger":"controller_multiclusterhub","msg":"Found image overrides from environment variables set by operand image prefix"}
{"level":"info","ts":1624453196.3947287,"msg":"Enforcing pod volumes","Deployment.Namespace":"open-cluster-management","Deployment.Name":"ocm-webhook"}
{"level":"info","ts":1624453196.562023,"logger":"controller_multiclusterhub","msg":"Ensuring managed cluster hub resources are removed"}
{"level":"info","ts":1624453198.6044412,"logger":"controller_multiclusterhub","msg":"Reconciling MultiClusterHub","Request.Namespace":"open-cluster-management","Request.Name":"multiclusterhub"}
{"level":"info","ts":1624453198.6344895,"logger":"controller_multiclusterhub","msg":"Found image overrides from environment variables set by operand image prefix"}
{"level":"info","ts":1624453198.9466665,"msg":"Enforcing pod volumes","Deployment.Namespace":"open-cluster-management","Deployment.Name":"ocm-webhook"}
{"level":"info","ts":1624453199.0863216,"logger":"controller_multiclusterhub","msg":"Ensuring managed cluster hub resources are removed"}
{"level":"info","ts":1624453199.207741,"logger":"controller_multiclusterhub","msg":"Reconciling MultiClusterHub","Request.Namespace":"open-cluster-management","Request.Name":"multiclusterhub"}
{"level":"info","ts":1624453199.2318418,"logger":"controller_multiclusterhub","msg":"Found image overrides from environment variables set by operand image prefix"}
{"level":"info","ts":1624453199.614601,"msg":"Enforcing pod volumes","Deployment.Namespace":"open-cluster-management","Deployment.Name":"ocm-webhook"}
```

**Comment by JakobGray** [comment]
Since the deployment getting logged is `ocm-webhook` I don't think it's related to this PR.

**Comment by zhiweiyin318** [comment]
@JakobGray I think the log is caused by that ocm-webhook pod mounts the cert secret ocm-webhook created by OCP after the service ocm-webhook is created. the cert secret ocm-webhook is missing before the service ocm-webhook is created.

**Pull request merged**
